# Site settings
title: Gregory Jacobs
email: greg@greg-jacobs.com
description: > # this means to ignore newlines until "baseurl:"
  My website with me, my résumé, and links to my works.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregjacobs.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: gregjacobs

# Build settings
markdown: kramdown
